### PR TITLE
use CRLF line endings in src/TweetSharp.Mono/Newtonsoft.Json.xml - VS…

### PR DESCRIPTION
**Pull request by collinsauve**
… continually makes this change

Not sure if there is some other reason to use LF in this file.   Very annoying to have to constantly reset this file in git.

### CODE REVIEW

**Comment by Yortw** [comment]
I'm not sure why it's like this either, but I presume it comes from the Json.Net package so I'm not sure we can fix it our side?

**Comment by collinsauve** [comment]
I believe I just needed to set my git config for this project properly.  I set the following in my `.git/config`:

```
[core]
	eol = lf
	autocrlf = input
```

You probably work with git settings that commit LFs, and I was working with "commit as-is".

**Comment by Yortw** [comment]
Thanks, ill check mine later. I had some trouble with .cs files last night in VS saying the line endings were LF and it wanted CRLF, which I haven't had before. Not sure what is doing that.

**Comment by Yortw** [comment]
I have neither of those settings explicitly set in my .git/config. Does that mean it should be 'commit as-is'?

Also confused about why the Newtonsoft.Json.xml file would have changed even if I did - I don't open or edit the file as far as I'm aware, so it shouldn't change?

**Comment by collinsauve** [comment]
Perhaps you have it set in your global gitconfig? Do you have a `%USERPROFILE%\.gitconfig` file?

**Comment by Yortw** [comment]
Nope, it's not set there either. I've also noticed that since your changes, things like the nuspec file no longer have the correct line breaks when viewed in notepad. I'm pretty sure (but not certain) my system is set to use CRLF - the newtonsoft.json.xml file isn't one I edit, it should be coming from the json.net nuget package, so maybe they use lf.

**Pull request merged**
