### PR TITLE
use git protocol for submodule

### PR DESCRIPTION
**Pull request by collinsauve**

### CODE REVIEW

**Comment by Yortw** [comment]
At work at the moment so I don't have time to look at this but will try tonight (though I am busy this evening too). The other two PR's look ok at a glance, but this one has caused the CI build to fail. I'm not particularly familiar with Git so I'm not sure how to solve the problem. I'm also not sure why this was required because I *thought* had already implemented Hammock as a submodule. In any case, the build log shows;

15git submodule -q update --init --recursive
 16Permission denied (publickey).
 17fatal: Could not read from remote repository

So it appears to be either a security or address related problem.
If you know better than me and can provide advise/a fix, then I'm happy to receive the help. Thanks.

**Comment by Yortw** [comment]
PS: Thanks heaps for the PR's, I appreciate the help.

**Comment by collinsauve** [comment]
This PR isn't very necessary... some clients (including mine at the moment) have trouble with https connections.

**Comment by collinsauve** [comment]
Actually while we're talking about the submodule, may I ask: can this be turned into a Nuget package instead?  In my experience, submodules have several "gotchas" and generally have fallen out of favour.

https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/

**Comment by Yortw** [comment]
Possibly but since I don't actually own either package and since I only support Hammock to make TweetMoaSharp work (not as a standard alone entity) I'm loathe to publish my own version. The original author seems to have had them separate, then gone to submodules, then moved to just including Haammock repo as a clone into the TweetSharp repo (or similar) because too many people struggled to make every previous attempt work when the cloned the repository. I'm not sure what's best, but the submodule (which I am not at all an expert in) has worked better for me than the direct clone that I got initially from the parent repo.

**Comment by collinsauve** [comment]
I wasn't aware that there wasn't a recent Hammock version on Nuget.

If it works for you, as the main contributor, who am I to disagree :)

P.S. No problem for the PRs - I've been using your library in production for almost a year now, happy to give back.

**Comment by Yortw** [comment]
Glad to hear you're using it successfully, and thanks again for the PR's/assistance.
Happy to make this change if I can figure out how to make it work everywhere.

**Pull request closed without merging**
